const UPDATE_FILTER = "UPDATE_FILTER";
const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";
const TOGGLE_SIGNUP_MODAL = "TOGGLE_SIGNUP_MODAL";

export { UPDATE_FILTER, TOGGLE_LOGIN_MODAL, TOGGLE_SIGNUP_MODAL };
